### ISSUE TITLE
RFC: dynamic entity creation and deletion

### ISSUE THREAD

**Issue by kvark** [kvark/parsec#11]
Dynamic operation means that it happens during a system execution as opposed to being outside of the system processing (this is already in).

### Appendix
We could add `RwLock<Appendix>` to the `Scheduler`, where:
```rust
struct Appendix {
    next: Entity,
    queue: Vec<Entity>,
}
```
Note: `World` doesn't know anything about it.
Then, `WorldArg` would get methods `insert() -> Entity` and `remove(Entity)`. These would lock the `Appendix` for writing and update both `next` and the `queue`.

Note: when removing an entity, the value added to the queue can have its generation inverted right away. This allows to avoid having two separate queues for insertion/removal, or an additional enum type.
Note: we propose `next: Entity` instead of `next_free: Index`, because when an entity gets dynamically deleted, we can no longer use `generations` vector for its new generation.

### Latency
We want the newly created entities to start participating right away. The use-case is: player input generates a bullet, it gets its first movement and rendered the same frame.
Note: removing entities doesn't have to have low latency. E.g. if the player killed something, it's more important to show the explosion particles quickly than hiding the object itself.

Locking `generations` for writing is not an option, since it's getting used simultaneously by multiple systems all the time (fore reading). Thus, we record entity insertion and removal in the `Appendix`.

In order to be able to work with the new entities, we propose having `entities_extra(&self) -> EntitiesExtraIter` method in the `WorldArg`. It would lock the appendix for reading, go through the queue, and return those entities that were added. We can also update the `run` method to always process extra entities by default, or make it configurable.

Note: we don't force the user to iterate over extra entities in their custom systems. It's their decision, and they can even decide on that dynamically during the system execution.

### Rest
Of course, we should not be using the appendix across multiple frames without merging it with the world. Otherwise we'd suffer from the lock waits. To address this, we could have a `rest()` method in the scheduler. The implementation would lock both `world.generations` and `appendix` for writing, thus waiting for all the systems to finish. Then we'd record the queued changes into the generation changes, and clear the queue.

User is supposed to call `rest` at the end of the frame, where waiting is allowed. It's an open question of how to enforce that. Perhaps, we can assert or warn when the size of the queue reaches a certain fraction of the world.

**Comment by csherratt** [comment]
My only issue is in how this interacts with the current components. Right now we iterator against a `Vec<Entitty>` to know what is alive and what we should try and inspect. We still need a way to communicate that new entities are present to downstream readers.

Maybe a solution could be to get ride of the current `entities` array and just do a direct join instead.

**Comment by kvark** [comment]
@csherratt
> Right now we iterator against a Vec<Entitty>

There is actually no `Vec<Entity>` any more. The iterator makes entities on the fly based on the generation vector.

> We still need a way to communicate that new entities are present to downstream readers.

The current approach somewhat works. Supposing that system B needs to work on the new entities created by system A.
  - B should be queued after A
  - A adds an entity, which appears in the appendix queue
  - B first iterates old entities, then it iterates `warg.extra_entities()`, by which point A has hopefully already added the entities (that's a tricky point).

I was thinking about directly changing the generations array, but this seems to be difficult to get without overhead.
